// /Users/remruata/projects/cid-ai/src/components/ui/ExampleTheme.ts
export const ExampleTheme = {
  ltr: "text-left",
  rtl: "text-right",
  placeholder:
    "text-gray-400 absolute top-3 left-3 select-none inline-block pointer-events-none",
  paragraph:
    "block w-full m-0 mb-2 relative whitespace-pre-wrap text-left break-words leading-relaxed",
  heading: {
    h1: "block text-2xl font-bold mb-3 w-full whitespace-pre-wrap text-left",
    h2: "block text-xl font-semibold mb-2 w-full whitespace-pre-wrap text-left",
    h3: "block text-lg font-medium mb-1 w-full whitespace-pre-wrap text-left",
  },
  list: {
    ul: "block list-disc pl-6 mb-2 w-full",
    ol: "block list-decimal pl-6 mb-2 w-full",
  },
  listItem: "block mb-1 w-full whitespace-pre-wrap text-left",
  quote:
    "block border-l-4 border-gray-300 pl-4 italic text-gray-600 mb-2 w-full whitespace-pre-wrap text-left",
  code: "block bg-gray-100 p-2 rounded text-sm font-mono whitespace-pre-wrap mb-2 w-full text-left",
  codeHighlight: {
    atrule: "text-purple-600",
    attr: "text-blue-600",
    boolean: "text-red-600",
    builtin: "text-purple-600",
    cdata: "text-gray-600",
    char: "text-green-600",
    class: "text-blue-600",
    "class-name": "text-blue-600",
    comment: "text-gray-500 italic",
    constant: "text-red-600",
    deleted: "text-red-600",
    doctype: "text-gray-600",
    entity: "text-red-600",
    function: "text-purple-600",
    important: "text-red-600",
    inserted: "text-green-600",
    keyword: "text-purple-600",
    namespace: "text-red-600",
    number: "text-red-600",
    operator: "text-gray-700",
    prolog: "text-gray-600",
    property: "text-blue-600",
    punctuation: "text-gray-700",
    regex: "text-green-600",
    selector: "text-green-600",
    string: "text-green-600",
    symbol: "text-red-600",
    tag: "text-red-600",
    url: "text-blue-600",
    variable: "text-red-600",
  },
  link: "text-blue-600 hover:underline inline",
  text: {
    bold: "font-bold inline",
    italic: "italic inline",
    underline: "underline inline",
    strikethrough: "line-through inline",
    underlineStrikethrough: "underline line-through inline",
    code: "bg-gray-100 px-1 py-0.5 rounded text-sm font-mono inline",
    subscript: "text-xs align-sub inline",
    superscript: "text-xs align-super inline",
  },
};
